apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: monitoring
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type regexp
        expression /^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z) (?<stream>stdout|stderr) [A-Z] (?<log>.*)$/
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>

    <filter kubernetes.**>
      @type grep
      <regexp>
        key $.kubernetes.namespace_name
        pattern ^akash-services$
      </regexp>
    </filter>

    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        cluster cluster1
        node ${record.dig("kubernetes", "host") || "unknown"}
      </record>
    </filter>

    <match kubernetes.**>
      @type loki
      url http://<URL of Loki>:3100
      extra_labels {"cluster":"cluster1"}
      label_keys cluster,node
      flush_interval 10s
      flush_at_shutdown true
      buffer_chunk_limit 1m
    </match>
