apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: monitoring
data:
  fluent.conf: |
    <system>
      log_level info
    </system>

    <source>
      @type tail
      path /var/log/containers/akash-provider-0_akash-services_*.log
      pos_file /var/log/fluentd-akash-provider-0.log.pos
      read_from_head true
      tag akash-provider
      <parse>
        @type none
      </parse>
    </source>

    <filter **akash-provider**>
      @type record_transformer
      <record>
        cluster "europlots-sandbox"
        pod "akash-provider-0"
      </record>
    </filter>

    <match **akash-provider**>
      @type loki
      url "http://100.69.175.78:31000"
      extra_labels {"job":"fluentd"}
      <label>
        cluster ${record['cluster']}
        pod ${record['pod']}
      </label>
      <buffer>
        flush_interval 5s
        chunk_limit_size 1m
        retry_forever true
        retry_max_interval 30
        overflow_action block
      </buffer>
    </match>

    <source>
      @type tail
      path /var/log/containers/operator-inventory*.log
      pos_file /var/log/fluentd-operator-inventory.log.pos
      read_from_head true
      tag operator-inventory
      <parse>
        @type none
      </parse>
    </source>

    <filter **operator-inventory**>
      @type record_transformer
      <record>
        cluster "europlots-sandbox"
        pod "operator-inventory"
      </record>
    </filter>

    <match **operator-inventory**>
      @type loki
      url "http://100.69.175.78:31000"
      extra_labels {"job":"fluentd"}
      <label>
        cluster ${record['cluster']}
        pod ${record['pod']}
      </label>
      <buffer>
        flush_interval 5s
        chunk_limit_size 1m
        retry_forever true
        retry_max_interval 30
        overflow_action block
      </buffer>
    </match>

    <source>
      @type tail
      path /var/log/containers/operator-hostname*.log
      pos_file /var/log/fluentd-operator-hostname.log.pos
      read_from_head true
      tag operator-hostname
      <parse>
        @type none
      </parse>
    </source>

    <filter **operator-hostname**>
      @type record_transformer
      <record>
        cluster "europlots-sandbox"
        pod "operator-hostname"
      </record>
    </filter>

    <match **operator-hostname**>
      @type loki
      url "http://100.69.175.78:31000"
      extra_labels {"job":"fluentd"}
      <label>
        cluster ${record['cluster']}
        pod ${record['pod']}
      </label>
      <buffer>
        flush_interval 5s
        chunk_limit_size 1m
        retry_forever true
        retry_max_interval 30
        overflow_action block
      </buffer>
    </match>
