apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: monitoring
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      <parse>
        @type json
      </parse>
      read_from_head true
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <filter kubernetes.**>
      @type record_transformer
      <record>
        cluster_name CLUSTER_NAME_HERE
      </record>
    </filter>

    <filter kubernetes.**>
      @type grep
      <regexp>
        key $.kubernetes.namespace_name
        pattern ^akash-services$
      </regexp>
    </filter>

    <match kubernetes.akash-services.**>
      @type loki
      url "http://loki:3100/loki/api/v1/push"
      flush_interval 5s
      label_keys kubernetes,app,cluster_name
      remove_keys kubernetes
    </match>
