schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
storage_config:
  boltdb_shipper:
    shared_store: filesystem
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
compactor:
  working_directory: /var/loki/compactor
  shared_store: filesystem
  retention_enabled: true
limits_config:
  retention_period: 168h # 168 hours equals 7 days
