apiVersion: v1
kind: Service
metadata:
  name: loki-nodeport
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 3100
      targetPort: 3100
      nodePort: 31000
  selector:
    app: loki
