apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush 1
        Daemon off
        Log_Level info
        Parsers_File parsers.conf

    # Staging namespace logs
    [INPUT]
        Name tail
        Tag kube.var.log.containers.staging
        Path /var/log/containers/*_staging_*.log
        Parser docker
        Refresh_Interval 10
        Mem_Buf_Limit 5MB
        Skip_Long_Lines on

    [FILTER]
        Name kubernetes
        Match kube.var.log.containers.staging
        Merge_Log on
        Keep_Log off
        K8S-Logging.Parser on
        K8S-Logging.Exclude off

    [FILTER]
        Name modify
        Match kube.var.log.containers.staging
        Add log_source provider-console

    [OUTPUT]
        Name loki
        Match kube.var.log.containers.staging
        Host <host>
        Port 32100
        Labels log_source=provider-console
        Label_Keys $log_source
        Line_Format json
        Auto_Kubernetes_Labels false

  parsers.conf: |
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On
