apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  local-config.yaml: |
    auth_enabled: false
    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
    schema_config:
      configs:
        - from: 2020-05-15
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage_config:
      filesystem:
        directory: /loki/chunks
      tsdb_shipper:
        active_index_directory: /loki/tsdb-index
        cache_location: /loki/tsdb-cache
    compactor:
      working_directory: /loki/compactor
    limits_config:
      allow_structured_metadata: true
      reject_old_samples: true
      ingestion_rate_mb: 16  # Increase this value (was likely 4 by default)
      ingestion_burst_size_mb: 32  # Increase this value (was likely 8 by default)
      max_streams_per_user: 30000  # Increase this if hitting stream limits
      max_global_streams_per_user: 100000  # Increase for global stream limits
      reject_old_samples_max_age: 360h    # 15 days

      reject_old_samples_max_age: 720h    # 30 days
      creation_grace_period: 720h         # 30 days
      retention_period: 720h              # 30 days
