apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: {{ .Values.namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush 1
        Daemon off
        Log_Level info
        Parsers_File parsers.conf

    # akash-provider
    [INPUT]
        Name tail
        Tag kube.var.log.containers.akash-provider-0_${HOSTNAME}
        Path /var/log/containers/akash-provider-0_*.log
        Parser docker
        Refresh_Interval 10
        Mem_Buf_Limit 5MB
        Skip_Long_Lines on

    [FILTER]
        Name kubernetes
        Match kube.var.log.containers.akash-provider*
        Merge_Log on
        Keep_Log off
        K8S-Logging.Parser on
        K8S-Logging.Exclude off

    [FILTER]
        Name modify
        Match kube.var.log.containers.akash-provider*
        Add cluster_name {{ .Values.clusterName }}
        Add container_name akash-provider-0

    # Primary output for akash-provider
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.akash-provider*
        Host {{ .Values.loki.host }}
        Port {{ .Values.loki.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=akash-provider-0
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false

    # Secondary output for akash-provider (if configured)
    {{- if .Values.loki.secondary.host }}
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.akash-provider*
        Host {{ .Values.loki.secondary.host }}
        Port {{ .Values.loki.secondary.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=akash-provider-0
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false
    {{- end }}

    # Tertiary output for akash-provider (if configured)
    {{- if .Values.loki.tertiary.host }}
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.akash-provider*
        Host {{ .Values.loki.tertiary.host }}
        Port {{ .Values.loki.tertiary.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=akash-provider-0
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false
    {{- end }}

    # operator-hostname
    [INPUT]
        Name tail
        Tag kube.var.log.containers.operator-hostname_${HOSTNAME}
        Path /var/log/containers/operator-hostname-*.log
        Parser docker
        Refresh_Interval 10
        Mem_Buf_Limit 5MB
        Skip_Long_Lines on

    [FILTER]
        Name kubernetes
        Match kube.var.log.containers.operator-hostname*
        Merge_Log on
        Keep_Log off
        K8S-Logging.Parser on
        K8S-Logging.Exclude off

    [FILTER]
        Name modify
        Match kube.var.log.containers.operator-hostname*
        Add cluster_name {{ .Values.clusterName }}
        Add container_name operator-hostname

    # Primary output for operator-hostname
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-hostname*
        Host {{ .Values.loki.host }}
        Port {{ .Values.loki.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=operator-hostname
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false

    # Secondary output for operator-hostname (if configured)
    {{- if .Values.loki.secondary.host }}
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-hostname*
        Host {{ .Values.loki.secondary.host }}
        Port {{ .Values.loki.secondary.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=operator-hostname
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false
    {{- end }}

    # Tertiary output for operator-hostname (if configured)
    {{- if .Values.loki.tertiary.host }}
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-hostname*
        Host {{ .Values.loki.tertiary.host }}
        Port {{ .Values.loki.tertiary.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=operator-hostname
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false
    {{- end }}

    # operator-inventory
    [INPUT]
        Name tail
        Tag kube.var.log.containers.operator-inventory_${HOSTNAME}
        Path /var/log/containers/operator-inventory-*.log
        Parser docker
        Refresh_Interval 10
        Mem_Buf_Limit 5MB
        Skip_Long_Lines on

    [FILTER]
        Name kubernetes
        Match kube.var.log.containers.operator-inventory*
        Merge_Log on
        Keep_Log off
        K8S-Logging.Parser on
        K8S-Logging.Exclude off

    [FILTER]
        Name modify
        Match kube.var.log.containers.operator-inventory*
        Add cluster_name {{ .Values.clusterName }}
        Add container_name operator-inventory

    # Primary output for operator-inventory
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-inventory*
        Host {{ .Values.loki.host }}
        Port {{ .Values.loki.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=operator-inventory
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false

    # Secondary output for operator-inventory (if configured)
    {{- if .Values.loki.secondary.host }}
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-inventory*
        Host {{ .Values.loki.secondary.host }}
        Port {{ .Values.loki.secondary.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=operator-inventory
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false
    {{- end }}

    # Tertiary output for operator-inventory (if configured)
    {{- if .Values.loki.tertiary.host }}
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-inventory*
        Host {{ .Values.loki.tertiary.host }}
        Port {{ .Values.loki.tertiary.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=operator-inventory
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false
    {{- end }}

    # operator-inventory-hardware-discovery
    [INPUT]
        Name tail
        Tag kube.var.log.containers.operator-inventory-hardware-discovery_${HOSTNAME}
        Path /var/log/containers/operator-inventory-hardware-discovery-*.log
        Parser docker
        Refresh_Interval 10
        Mem_Buf_Limit 5MB
        Skip_Long_Lines on

    [FILTER]
        Name kubernetes
        Match kube.var.log.containers.operator-inventory-hardware*
        Merge_Log on
        Keep_Log off
        K8S-Logging.Parser on
        K8S-Logging.Exclude off

    [FILTER]
        Name modify
        Match kube.var.log.containers.operator-inventory-hardware*
        Add cluster_name {{ .Values.clusterName }}
        Add container_name operator-inventory-hardware-discovery

    # Primary output for operator-inventory-hardware-discovery
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-inventory-hardware*
        Host {{ .Values.loki.host }}
        Port {{ .Values.loki.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=operator-inventory-hardware-discovery
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false

    # Secondary output for operator-inventory-hardware-discovery (if configured)
    {{- if .Values.loki.secondary.host }}
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-inventory-hardware*
        Host {{ .Values.loki.secondary.host }}
        Port {{ .Values.loki.secondary.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=operator-inventory-hardware-discovery
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false
    {{- end }}

    # Tertiary output for operator-inventory-hardware-discovery (if configured)
    {{- if .Values.loki.tertiary.host }}
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-inventory-hardware*
        Host {{ .Values.loki.tertiary.host }}
        Port {{ .Values.loki.tertiary.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=operator-inventory-hardware-discovery
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false
    {{- end }}

    # operator-ip
    [INPUT]
        Name tail
        Tag kube.var.log.containers.operator-ip_${HOSTNAME}
        Path /var/log/containers/operator-ip-*.log
        Parser docker
        Refresh_Interval 10
        Mem_Buf_Limit 5MB
        Skip_Long_Lines on

    [FILTER]
        Name kubernetes
        Match kube.var.log.containers.operator-ip*
        Merge_Log on
        Keep_Log off
        K8S-Logging.Parser on
        K8S-Logging.Exclude off

    [FILTER]
        Name modify
        Match kube.var.log.containers.operator-ip*
        Add cluster_name {{ .Values.clusterName }}
        Add container_name operator-ip

    # Primary output for operator-ip
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-ip*
        Host {{ .Values.loki.host }}
        Port {{ .Values.loki.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=operator-ip
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false

    # Secondary output for operator-ip (if configured)
    {{- if .Values.loki.secondary.host }}
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-ip*
        Host {{ .Values.loki.secondary.host }}
        Port {{ .Values.loki.secondary.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=operator-ip
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false
    {{- end }}

    # Tertiary output for operator-ip (if configured)
    {{- if .Values.loki.tertiary.host }}
    [OUTPUT]
        Name loki
        Match kube.var.log.containers.operator-ip*
        Host {{ .Values.loki.tertiary.host }}
        Port {{ .Values.loki.tertiary.port }}
        Labels cluster_name={{ .Values.clusterName }},container_name=operator-ip
        Label_Keys $cluster_name,$container_name
        Line_Format json
        Auto_Kubernetes_Labels false
    {{- end }}

    # Kubernetes Events Input
    [INPUT]
        Name              kubernetes_events
        Tag               kube.events
        Interval_Sec      1
        Kube_URL         https://kubernetes.default.svc:443
        Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Token_TTL   600

    [FILTER]
        Name          modify
        Match         kube.events
        Add          cluster_name {{ .Values.clusterName }}
        Add          log_type kubernetes_events

    # Primary output for Kubernetes events
    [OUTPUT]
        Name          loki
        Match         kube.events
        Host          {{ .Values.loki.host }}
        Port          {{ .Values.loki.port }}
        Labels        cluster_name={{ .Values.clusterName }},log_type=kubernetes_events
        Label_Keys    $cluster_name,$log_type
        Line_Format   json
        Auto_Kubernetes_Labels false

    # Secondary output for Kubernetes events (if configured)
    {{- if .Values.loki.secondary.host }}
    [OUTPUT]
        Name          loki
        Match         kube.events
        Host          {{ .Values.loki.secondary.host }}
        Port          {{ .Values.loki.secondary.port }}
        Labels        cluster_name={{ .Values.clusterName }},log_type=kubernetes_events
        Label_Keys    $cluster_name,$log_type
        Line_Format   json
        Auto_Kubernetes_Labels false
    {{- end }}

    # Tertiary output for Kubernetes events (if configured)
    {{- if .Values.loki.tertiary.host }}
    [OUTPUT]
        Name          loki
        Match         kube.events
        Host          {{ .Values.loki.tertiary.host }}
        Port          {{ .Values.loki.tertiary.port }}
        Labels        cluster_name={{ .Values.clusterName }},log_type=kubernetes_events
        Label_Keys    $cluster_name,$log_type
        Line_Format   json
        Auto_Kubernetes_Labels false
    {{- end }}

  parsers.conf: |
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On
