apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-role
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - events
    verbs: ["get", "list", "watch"]
  - apiGroups: 
      - "apps"
      - "batch"
      - "autoscaling"
      - "networking.k8s.io"
      - "storage.k8s.io"
    resources: ["*"]
    verbs: ["get", "list", "watch"]
