apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-role
rules:
- apiGroups: [""]
  resources:
    - namespaces
    - pods
    - events
  verbs: ["get", "list", "watch"]
